name: CI/CD Spring Boot API

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Construir a aplicação
        run: mvn clean package -DskipTests

      - name: Rodar testes
        run: mvn test

  docker:
    name: Build e Push Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-api:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/springboot-api:latest ${{ secrets.DOCKER_USERNAME }}/springboot-api:${{ github.sha }}

      - name: Push da imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-api:${{ github.sha }}

  deploy:
    name: Deploy para Servidor
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: SSH e Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-api:latest
            docker stop springboot-api || true
            docker rm springboot-api || true
            docker run -d --name springboot-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/springboot-api:latest
