name: CI/CD Spring Boot AWS

on:
  push:
    branches:
      - develop
      - staging

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Rodar testes
        run: mvn test

      - name: Construir aplicação
        run: mvn clean package -DskipTests

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  docker:
    name: Build e Push Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target

      - name: Login no AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build da imagem Docker
        run: |
          docker build -t myapp:${{ github.sha }} .
          docker tag myapp:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/myapp:${{ github.sha }}

      - name: Push da imagem para o ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/myapp:${{ github.sha }}

  deploy:
    name: Deploy AWS ECS
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: AWS CLI Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Atualizar ECS Service
        run: |
          aws ecs update-service --cluster myapp-cluster --service myapp-service --force-new-deployment
